GET http://localhost:5276/tesco
###

GET http://localhost:5276/asda
###

GET http://localhost:5276/tesco/1
###

GET http://localhost:5276/asda/1
###

POST http://localhost:5276/tesco
content-type: application/json

{
  "id": 1,
  "name": "milk",
  "amount": 1,
  "hasObtained": false
}
###

POST http://localhost:5276/asda
content-type: application/json

{
  "id": 1,
  "name": "milk",
  "amount": 1,
  "hasObtained": false
}
###

DELETE http://localhost:5276/tesco/1

###

DELETE http://localhost:5276/asda/1

###